In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pandas_profiling import ProfileReport

In [2]:
df = pd.read_csv('drive_stats_2019_Q1/2019-01-01.csv')

In [3]:
df.shape

(106918, 129)

In [25]:
drive_models = df.groupby(by='model').count()

In [26]:
drive_models.head()

,date,serial_number,capacity_bytes,failure,smart_1_normalized,smart_1_raw,smart_2_normalized,smart_2_raw,smart_3_normalized,smart_3_raw,...,smart_250_normalized,smart_250_raw,smart_251_normalized,smart_251_raw,smart_252_normalized,smart_252_raw,smart_254_normalized,smart_254_raw,smart_255_normalized,smart_255_raw
model,,,,,,,,,,,,,,,,,,,,,
HGST HDS5C4040ALE630,50,50,50,50,50,50,50,50,50,50,...,0,0,0,0,0,0,0,0,0,0
HGST HMS5C4040ALE640,4674,4674,4674,4674,4674,4674,4674,4674,4674,4674,...,0,0,0,0,0,0,0,0,0,0
HGST HMS5C4040BLE640,14550,14550,14550,14550,14550,14550,14550,14550,14550,14550,...,0,0,0,0,0,0,0,0,0,0
HGST HMS5C4040BLE641,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
HGST HUH721010ALE600,10,10,10,10,10,10,10,10,10,10,...,0,0,0,0,0,0,0,0,0,0

In [27]:
drive_models = drive_models.serial_number.reset_index().rename(columns={'serial_number':'count'})

In [29]:
drive_models

                                  model  count
0                  HGST HDS5C4040ALE630     50
1                  HGST HMS5C4040ALE640   4674
2                  HGST HMS5C4040BLE640  14550
3                  HGST HMS5C4040BLE641      1
4                  HGST HUH721010ALE600     10
5                  HGST HUH721212ALN604   1278
6                  HGST HUH728080ALE600   1045
7                  HGST HUS726040ALE610     28
8               Hitachi HDS5C4040ALE630     14
9               Hitachi HDS724040ALE640      1
10                        ST10000NM0086   1210
11                       ST1000LM024 HN      1
12                        ST12000NM0007  31147
13                        ST250LM004 HN      1
14                          ST3160316AS      3
15                          ST3160318AS      1
16                           ST320LT007      1
17                          ST4000DM000  23153
18                          ST4000DM005     58
19                        ST500LM012 HN    604
20                           ST500LM030    111
21                          ST6000DM001     13
22                          ST6000DM004      2
23                          ST6000DX000   1524
24                          ST8000DM002   9874
25                          ST8000DM004      4
26                          ST8000DM005     25
27                         ST8000NM0055  14381
28  Seagate BarraCuda SSD ZA2000CM10002      1
29   Seagate BarraCuda SSD ZA500CM10002     13
30                      TOSHIBA HDWE160     10
31                      TOSHIBA HDWF180     20
32                  TOSHIBA MD04ABA400V    141
33                  TOSHIBA MD04ABA500V     45
34                  TOSHIBA MG07ACA14TA   1217
35                   TOSHIBA MQ01ABF050    528
36                  TOSHIBA MQ01ABF050M    354
37                       WDC WD1600AAJS     19
38                       WDC WD2500AAJS      1
39                       WDC WD3200AAJS      1
40                       WDC WD3200BEKX      1
41                         WDC WD40EFRX      2
42                       WDC WD5000BPKT     11
43                       WDC WD5000LPCX     56
44                       WDC WD5000LPVX    270
45                         WDC WD60EFRX    382

In [32]:
models = drive_models['model'].tolist()

In [33]:
models

['HGST HDS5C4040ALE630',
 'HGST HMS5C4040ALE640',
 'HGST HMS5C4040BLE640',
 'HGST HMS5C4040BLE641',
 'HGST HUH721010ALE600',
 'HGST HUH721212ALN604',
 'HGST HUH728080ALE600',
 'HGST HUS726040ALE610',
 'Hitachi HDS5C4040ALE630',
 'Hitachi HDS724040ALE640',
 'ST10000NM0086',
 'ST1000LM024 HN',
 'ST12000NM0007',
 'ST250LM004 HN',
 'ST3160316AS',
 'ST3160318AS',
 'ST320LT007',
 'ST4000DM000',
 'ST4000DM005',
 'ST500LM012 HN',
 'ST500LM030',
 'ST6000DM001',
 'ST6000DM004',
 'ST6000DX000',
 'ST8000DM002',
 'ST8000DM004',
 'ST8000DM005',
 'ST8000NM0055',
 'Seagate BarraCuda SSD ZA2000CM10002',
 'Seagate BarraCuda SSD ZA500CM10002',
 'TOSHIBA HDWE160',
 'TOSHIBA HDWF180',
 'TOSHIBA MD04ABA400V',
 'TOSHIBA MD04ABA500V',
 'TOSHIBA MG07ACA14TA',
 'TOSHIBA MQ01ABF050',
 'TOSHIBA MQ01ABF050M',
 'WDC WD1600AAJS',
 'WDC WD2500AAJS',
 'WDC WD3200AAJS',
 'WDC WD3200BEKX',
 'WDC WD40EFRX',
 'WDC WD5000BPKT',
 'WDC WD5000LPCX',
 'WDC WD5000LPVX',
 'WDC WD60EFRX']

In [34]:
HGST_HDS5C4040ALE630 = df[df.model == 'HGST HDS5C4040ALE630']

In [53]:
names = [] # Empty list to hold new dataframe names

for model in models:
    name = model.replace(' ', '_')
    name = name.replace('-', '_')
    names.append(name)
    name = df[df.model == model]
    
print(names)

['HGST_HDS5C4040ALE630', 'HGST_HMS5C4040ALE640', 'HGST_HMS5C4040BLE640', 'HGST_HMS5C4040BLE641', 'HGST_HUH721010ALE600', 'HGST_HUH721212ALN604', 'HGST_HUH728080ALE600', 'HGST_HUS726040ALE610', 'Hitachi_HDS5C4040ALE630', 'Hitachi_HDS724040ALE640', 'ST10000NM0086', 'ST1000LM024_HN', 'ST12000NM0007', 'ST250LM004_HN', 'ST3160316AS', 'ST3160318AS', 'ST320LT007', 'ST4000DM000', 'ST4000DM005', 'ST500LM012_HN', 'ST500LM030', 'ST6000DM001', 'ST6000DM004', 'ST6000DX000', 'ST8000DM002', 'ST8000DM004', 'ST8000DM005', 'ST8000NM0055', 'Seagate_BarraCuda_SSD_ZA2000CM10002', 'Seagate_BarraCuda_SSD_ZA500CM10002', 'TOSHIBA_HDWE160', 'TOSHIBA_HDWF180', 'TOSHIBA_MD04ABA400V', 'TOSHIBA_MD04ABA500V', 'TOSHIBA_MG07ACA14TA', 'TOSHIBA_MQ01ABF050', 'TOSHIBA_MQ01ABF050M', 'WDC_WD1600AAJS', 'WDC_WD2500AAJS', 'WDC_WD3200AAJS', 'WDC_WD3200BEKX', 'WDC_WD40EFRX', 'WDC_WD5000BPKT', 'WDC_WD5000LPCX', 'WDC_WD5000LPVX', 'WDC_WD60EFRX']

In [56]:
print(name)

HGST_HDS5C4040ALE630

In [57]:
name.head()

AttributeError: 'str' object has no attribute 'head'